#! /usr/bin/env python3
"""Unix Processes.

Usage:
  basic.py hello 
  basic.py goodbye <name>
  basic.py add <x>
  basic.py (-h | --help)

Options:
  -h --help     Show this screen.

"""
from docopt import docopt
import psutil
from termcolor import colored, cprint
def process_id():
	for process in psutil.pids():
		p = psutil.Process(process)
		ids = colored(process,'green', attrs=['bold'])
		names = colored(p.name(),'cyan',attrs=['bold'])
		mem_usage = colored(p.memory_percent(), 'red',attrs=['bold']) 
		print('Process ID: ' + ids +' Name: ' + names+ ' mem_usage: '+mem_usage)

# process_id()







# text = colored('Hello, World!', 'green', attrs=[ 'blink','bol'])
# print(text)
# cprint('Hello, World!', 'green', 'on_red')







def hello():
	print("Hello")

#Commandline logic
if __name__ == '__main__':
    arguments = docopt(__doc__)

    # if an argument called hello was passed, execute the hello logic.
    if arguments['hello']:
    	process_id()